# Generated by Django 3.1.7 on 2022-01-30 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('proveedor', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('n_articulos', models.CharField(max_length=4)),
            ],
        ),
    ]
